<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Mappy</RootNamespace>
    <AssemblyName>Mappy</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>x86</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);1591;CA1416;WFO1000</NoWarn>
    <ApplicationIcon>Assets\mappy.ico</ApplicationIcon>
    <StartupObject>Mappy.Program</StartupObject>
    <NoWin32Manifest>true</NoWin32Manifest>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Properties\AssemblyInfo.cs.tmpl" />
    <None Include="Mappy.ruleset" />
    <None Include="Properties\DataSources\Mappy.Models.MapAttributesResult.datasource" />
    <None Update="default.json.sample">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Content Include="Assets\TA Palette.pal">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bugsnag" Version="4.1.1" />
    <PackageReference Include="Hjg.Pngcs" Version="1.1.5" />
    <PackageReference Include="Ookii.Dialogs.WinForms" Version="4.0.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\..\TAUtil\TAUtil\TAUtil.csproj" />
    <ProjectReference Include="..\..\TAUtil\TAUtil.Gdi\TAUtil.Gdi.csproj" />
    <ProjectReference Include="..\..\TAUtil\TAUtil.HpiUtil\TAUtil.HpiUtil.csproj" />
  </ItemGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Windows.Forms.AnchorLayoutV2" Value="true" Trim="false" />
  </ItemGroup>
  <Target Name="GenerateAssemblyInfo" BeforeTargets="BeforeBuild">
    <Exec Command="python &quot;$(MSBuildThisFileDirectory)..\GenerateAssemblyInfo.py&quot; &quot;$(MSBuildThisFileDirectory)&quot;" />
  </Target>
</Project>
