<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>WireframeViewer</RootNamespace>
    <AssemblyName>WireframeViewer</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>x86</Platforms>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\Mappy\Mappy.csproj" />
    <ProjectReference Include="..\..\TAUtil\TAUtil\TAUtil.csproj" />
  </ItemGroup>
</Project>
