<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Geometry</RootNamespace>
    <AssemblyName>Geometry</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Properties\AssemblyInfo.cs.tmpl" />
  </ItemGroup>
  <Target Name="GenerateAssemblyInfo" BeforeTargets="BeforeBuild">
    <Exec Command="python &quot;$(MSBuildThisFileDirectory)..\GenerateAssemblyInfo.py&quot; &quot;$(MSBuildThisFileDirectory)&quot;" />
  </Target>
</Project>
