<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>MappyTest</RootNamespace>
    <AssemblyName>MappyTest</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>x86</Platforms>
    <IsPackable>false</IsPackable>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mappy\Mappy.csproj" />
    <ProjectReference Include="..\..\TAUtil\TAUtil.Gdi\TAUtil.Gdi.csproj" />
  </ItemGroup>
</Project>
