name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Restore NuGet packages
        run: nuget restore Mappy.sln

      - name: Build Release
        run: msbuild Mappy.sln /p:Configuration=Release /p:Platform=x86 /m
